### PR TITLE
[Suggestion] Give priority to loopback address

### PR DESCRIPTION
**Pull request by Yanchi4425**
## Why
This issue is a suggestion and the code is experimental.

Multiple local IPs may be obtained when the "dev" command is executed.
The acquired address may change depending on the execution timing, so it is necessary to retrust it.

## What

If "127.0.0.1" is included in the acquired local addresses, I would like to give priority to setting it.

In addition, chrome has the ability to unconditionally trust the loopback address.
see: https://qiita.com/yanchi4425/items/76e502c41cbfb4f0542b

## Checklist

- [x] Read [README.md](https://github.com/kintone-labs/kintone-cli/blob/master/README.md)
- [ ] Updated documentation if it is required.
- [x] Checked the behavior.

### CODE REVIEW

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you very much for the improvement suggestion and I'm sorry to be late checking and responding to your PR.

We have considered it as below. What do you think?

In some companies, specifying pc name or static IP can access by team members' PC.
If using that IP, the developer can create customization and share it with team members for testing the app.
On the other hand, if accepting using only "https://127.0.0.1:8000/", only the developer can test it on his PC.

So we think it will be better to show all IPs and don't need to set the priority among them.
As for logic improvement, we think it is good to show all results from "ws" command and let the developer choose from the list.

**Comment by Yanchi4425** [comment]
@TomokoMiyake 

I thought I would only use the "--localhost" option if I needed to share it with our team members.
There is no problem with the content of your proposal!

Thank you

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
Thank you for your quick reply.
It sounds great. We will plan to improve in the near future.

**Comment by TomokoMiyake** [comment]
@Yanchi4425 
We have released v0.3.0 including the dev command IP list improvement.
Please check the detail here.
https://github.com/kintone-labs/kintone-cli/releases/tag/v0.3.0

Thank you!

**Pull request closed without merging**
